### ISSUE TITLE
About hrt.json

### ISSUE THREAD

**Issue by willer-lu** [THU-KEG/KB-Plugin#2]
For GrailQA, GraphQ and WebQ, how to get the file 'hrt.json' from the original dataset or knowledge base?
I know the file mentioned is provided, I just wonder how did it form. 
What's more, can you offer the training_set of the above datasets?

**Comment by Neo-Zhangjiajie** [comment]
We get the 'hrt.json' for GrailQA, GraphQ, and WebQ from the original RDF dump of Freebase. We first preprocessed the original dump following https://github.com/nchah/freebase-triples to obtain the clean triples. After that, we get the 'hrt.json' using the method mentioned in Section 4.2.2 and Appendix B in our paper: https://arxiv.org/pdf/2402.01619.pdf.  We did not provide relevant codes since they are too tedious and the intermediate files are huge.

The training sets can be found in https://github.com/dki-lab/ArcaneQA/tree/main/data.
