### ISSUE TITLE
About training epochs

### ISSUE THREAD

**Issue by willer-lu** [THU-KEG/KB-Plugin#3]

**Comment by willer-lu** [comment]
According to the paper, you train the schema plugins of the source and target KBs for 3 epochs and 1 epoch, respectively.But in the script like 'train_el_lora.sh' in 'transfer_freebase/sft_llama', the 'num_train_epochs' is set to 3, why?    
What's more, since the epochs of the source KBs  is set to 3, why 1 is enough for target KBs?

**Comment by Neo-Zhangjiajie** [comment]
Sorry, the "num_train_epochs=3" in 'train_el_lora.sh' in 'transfer_freebase/sft_llama' is a typo and we have fixed it.

For the second question, we set num_train_epochs=1 for target KBs since the target KBs have much more relations as well as triple samples than the source KBs. So we set num_train_epochs=1 for target KBs to (1) make the training steps on source KBs and target KBs close so that their schema plugins share more similar hidden distributions;  (2) save the training times.

**Comment by willer-lu** [comment]
> Sorry, the "num_train_epochs=3" in 'train_el_lora.sh' in 'transfer_freebase/sft_llama' is a typo and we have fixed it.
> 
> For the second question, we set num_train_epochs=1 for target KBs since the target KBs have much more relations as well as triple samples than the source KBs. So we set num_train_epochs=1 for target KBs to (1) make the training steps on source KBs and target KBs close so that their schema plugins share more similar hidden distributions; (2) save the training times.

Thanks!
Actually, the 'num_train_epochs' in transfer_domain_specific/sft_llama
/train_el_lora.sh and source_kqapro/sft_llama/train_pi_plugin.sh should be set to 1, is it right?

**Comment by Neo-Zhangjiajie** [comment]
Yes! I will change them.
